### ISSUE TITLE
Setting to delete the notes in Voicenotes once synchronized to Obsidian

### ISSUE THREAD

**Issue by dsebastien** [mysticcoders/voicenotes-sync#11]
First, thanks a lot for creating this plugin. I was about to do it ;-)

It would be awesome to have a setting such as "Delete notes once synchronized", to delete the notes in Voicenotes once synchronized. I personally don't want to keep those around once I have them in Obsidian.

**Comment by kinabalu** [comment]
I think this is possible, but it's also a bit risky as well -- how would we ensure sync was completed and user was ok with deleting the source info?

**Comment by kinabalu** [comment]
@dsebastien the latest plugin v0.0.9 now offers the ability to delete synced notes after a double-confirm.

**Comment by dsebastien** [comment]
Awesome. Thank you!
