### ISSUE TITLE
Bug: setting a custom path for storing voicenotes fails

### ISSUE THREAD

**Issue by dsebastien** [mysticcoders/voicenotes-sync#15]
After enabling the "Download audio" option and customizing the sync directory to "30 Areas/38 Voice notes" (a folder that exists), I received the following error on sync: 

![image](https://github.com/mysticcoders/voicenotes-sync/assets/89887/aacc62c0-ad67-443d-8837-1833e56b5beb)

**Comment by dsebastien** [comment]
The path construction code for the sync directory seems invalid

**Comment by kinabalu** [comment]
very curious indeed -- need to find a windows VM and install so I can test -- doesn't happen on MacOS and yeah, could be some cross-platform issue with how the directory is being constructed. looking into it

**Comment by kinabalu** [comment]
Got a vmware install with obsidian to test, this was a worthwhile update and should all be fixed up now
