### ISSUE TITLE
Can Todos have checkbox, not bullet?

### ISSUE THREAD

**Issue by qwertydude** [mysticcoders/voicenotes-sync#18]
Hey, just a little one... 

When you import the To Do lists created by Voicenotes, can you prefix them with a checkbox rather than a bullet?

Also, could you add a todo tag to each? Or provide an option for a custom tag to add to them.

Thanks

**Comment by kinabalu** [comment]
great suggestion and definitely needed -- added in 0.0.11 just now and a setting called `todoTag` which will let you append a tag to each todo.
