### ISSUE TITLE
TODOs undo when syncing

### ISSUE THREAD

**Issue by samwho** [mysticcoders/voicenotes-sync#20]
It seems like when this plugin sync with Voicenotes.com, all of the TODOs in my voice notes get undone. It's as if it does a full re-sync every time, and overwrites the notes with their original contents.

**Comment by kinabalu** [comment]
Heh it 100% does a full sync and overwrites if you hit "Manual Sync" otherwise it should see that it exists and ignore.

Could add a setting to add a "#synced" tag to the notes and if it exists then it never touches that note again regardless...?

Thoughts?

**Comment by kinabalu** [comment]
Changed functionality so now there are two buttons for Manual sync
- Manual sync (only syncs items that haven't been synced)
- Manual sync (overwrite) destructive and will overwrite

**Comment by samwho** [comment]
Ahh fantastic, thank you!

Really great plugin, thank you so much for the effort you've put in here.
