### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Leit-motif** [mysticcoders/voicenotes-sync#21]
I enter my username and password however clicking Login does not do anything.

**Comment by kinabalu** [comment]
Did you signup with email and password on voicenotes.com or using Apple, Google or Twitter?

**Comment by Nwan692** [comment]
I have the same problem. Signed up to voicenotes using Google link

**Comment by kinabalu** [comment]
Instructions on how you can login with one of those services available at https://github.com/mysticcoders/voicenotes-sync?tab=readme-ov-file#login-via-apple-google-twitter-x
