### ISSUE TITLE
FEATURE REQUEST: Prepend the current date to the title of the note within Obsidian

### ISSUE THREAD

**Issue by DrGump** [mysticcoders/voicenotes-sync#23]
Syncing works great! Thanks for developing this plugin. I would love to see the option in the plugin settings to prepend the current date to the title of the note.

**Comment by kinabalu** [comment]
Available now in 0.0.17. Uses YYYY-MM-DD as this probably is the most sensible default -- if there's a want to add an alternate format please open another ticket

**Comment by DrGump** [comment]
Perfect! Tested and it is working exactly as I had hoped. Thank you so much for the quick response and resolution!
