### ISSUE TITLE
Feature Request: Add Templates in the options config 

### ISSUE THREAD

**Issue by cvasanthk** [mysticcoders/voicenotes-sync#24]
to be able to select a template, which will be applied to voicenotes in the selected folder.

**Comment by kinabalu** [comment]
@cvasanthk interesting idea -- what were you thinking would be the template engine here? is there a specific plugin to integrate with like Templater?

**Comment by cvasanthk** [comment]
Hi Andrew, 
Yes, you are right. I was thinking about Templater. 
Currently the voicenotes sync works well. However the notes synced does not get a title for example. Also the yaml is limited and default to 
recording_id: 
duration: 5638 ( I should be able to convert this to hr: min:sec)
created_at: 2024-06-12T03:32:42.000000Z
updated_at: 2024-06-12T03:33:39.000000Z
created: 2024-06-12T08:28 ( I would like to use the Templater script here)
updated: 2024-06-14T19:39

Requirements: 
I would like to capture the title from voicenotes as -is. 
I want to create a file name with say {{date-title}}. 
I would like to import the tags if I have created in voicenotes. 

If I’m able to create it with  the Templater, with a voice note template, I think the above could be addressed. 

Is it doable? Sorry, I’m not a programmer and hence cannot suggest technical solutions here. 

Cheers, Vasanth

**Comment by kinabalu** [comment]
For reference the plugin being discussed here is https://github.com/SilentVoid13/Templater

**Comment by jor7am** [comment]
Is there any way to create a dataview to show created_at: 2024-06-12T03:32:42.000000Z as a standard date?

**Comment by kinabalu** [comment]
i think with the changes in 0.0.20 this is solved.
