### ISSUE TITLE
"Thread" compatibility

### ISSUE THREAD

**Issue by yshhwy** [mysticcoders/voicenotes-sync#31]
It appears that "Thread" notes are not syncing to Obsidian. It's a new feature, hope it to be supported soon.

**Comment by cvasanthk** [comment]
Yes, the Voicenotes has released the new feature to add sub notes to the parent note. This is a very useful feature from Voicenote. 

The added subnote /named as " Thread" note is not synced by the plugin currently. It will be help if this added "thread" note could be synched using the voicenotes-sync plugin.  thanks for the great work with this plugin.

**Comment by andrewlombardictr** [comment]
yeah looking into it, they have attachments now as well, and looking at how we want to represent these items in obsidian so they're synced properly

**Comment by yoghurtdewdew** [comment]
Very much looking forward to this!!

**Comment by YorVeX** [comment]
Yes please 🥺

**Comment by kinabalu** [comment]
Thread has been added thanks to @hjamet with 0.0.20 released now!

**Comment by cvasanthk** [comment]
Thank you!!! The sub thread notes gets linked to the main notes in Obsidian. Please refer to my test of the 0.0.20 release in #32.
