### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by aldrinjenson** [mysticcoders/voicenotes-sync#33]
Hi, Thank you for building this awesome plugin!

Small request to please add attachment support when you get some time

Atleast showing the links would be much appreciated. 

Thanks again!!

**Comment by kinabalu** [comment]
0.0.19 has support for downloading attachments now, hope that's helpful. was only able to see that they supported links and images which are both handled (the images get downloaded because the URL is a temporary URL)

Hope that helps!

**Comment by aldrinjenson** [comment]
Oh wow okay, Thank You for adding this!
