### ISSUE TITLE
Enhancing Note Presentation for Improved Readability and Usability

### ISSUE THREAD

**Issue by hjamet** [mysticcoders/voicenotes-sync#34]
I think it would be relevant to improve the presentation of notes to facilitate their reading and use. This would be a minor effort and a good improvement in my opinion. 🙃

Here are some ideas:

- Place the **summary/key points** at the top of the note if a summary or key points have been generated
- Replace the transcript with its **cleaned-up version** if such a version has been generated
- Replace the `created at` and `updated at` properties with dates in *Obsidian's date and time format* (I think we can do without milliseconds ^^)
- Replace the `duration` property with a readable format `.m.s`

What do you think? 🦦
PS : _I'd be delighted to work on it tomorrow if the idea appeals!_

**Comment by yshhwy** [comment]
These ideas are intriguing, can't wait to use them!

**Comment by kinabalu** [comment]
closed with #35 -- beta version available via BRAT and if no big issues come up we can push v0.0.20 out to everyone
