### ISSUE TITLE
Voicenotes tags separated by a space become two different tags

### ISSUE THREAD

**Issue by mickahouan** [mysticcoders/voicenotes-sync#38]
Do you think you could add a bottom line for Voicenotes tags separated by a space?
Today, tags separated by a space become several tags, which is not the intention...
Exemple : Écriture_libre

And I think the bottom dash would be preferable to the middle dash, as it would allow tags to be indented with sub-tags, which would make tag management less cluttered.

![image](https://github.com/user-attachments/assets/d0245459-3dfe-4aff-9fa9-b4179ec8b100)
![image](https://github.com/user-attachments/assets/916a7f52-2f31-40b6-a3e5-187f94cbfd00)

**Comment by kinabalu** [comment]
please reopen if 0.0.20 doesn't fix this but it should.
