### ISSUE TITLE
BETA -- Issues and minor improvements

### ISSUE THREAD

**Issue by hjamet** [mysticcoders/voicenotes-sync#41]
# 🎉 Voice Notes Sync Beta Discussion 🎙️

If you agree, I suggest using this issue to discuss the current Beta problems (which can be installed with [BRAT](https://github.com/TfTHacker/obsidian42-brat) using the following parameters:

## 🧊 Frozen Version
- Repository link: https://github.com/mysticcoders/voicenotes-sync
- Release tag: [0.0.20-beta](https://github.com/mysticcoders/voicenotes-sync/tree/0.0.20-beta)

## 🚀 Identified Improvements

For my part, I've identified the following improvements so far:

1. ✨ **Custom Note Template**: Not all available fields are present in the example. For instance, 'tweet' or 'blog' are missing. Moreover, the example could be improved.
2. 📏 **Template Editing Area**: Although resizable, the "Custom Note Template" area is far too small by default, making editing cumbersome.
3. 🐞 **Debug Mode**: Currently doesn't provide any value.
4. 🔄 **Sync Settings**: There's a duplication between "Sync Interval" and "Automatic Sync every".
5. 📅 **Date Format**: The current format is confusing. Additionally, it should be used in the `created_at` and `updated_at` fields (see [this comment](https://github.com/mysticcoders/voicenotes-sync/pull/35#issuecomment-2287981931)).

**Comment by giittyy** [comment]
I truly think the best way to fix the created_at and updated_at issue would be to give the option to edit frontmatter in the exact same way as the body of the document.

**Comment by kinabalu** [comment]
0.0.20 has been released. @hjamet would you mind looking through and closing the tickets that it has fixed? thank you again for all the work!

**Comment by hjamet** [comment]
> 0.0.20 has been released. @hjamet would you mind looking through and closing the tickets that it has fixed? thank you again for all the work!

Unfortunately, I just realized that I didn't have the necessary permissions to close the issues in question!
And thank you for the thanks, it was my pleasure ;)

**Comment by kinabalu** [comment]
@hjamet can you iterate the numbers and I'll look and review and make sure it covers with your latest update
