### ISSUE TITLE
custom instruction creations do not sync

### ISSUE THREAD

**Issue by yellowbluechameleon** [mysticcoders/voicenotes-sync#43]
Hi, first of all, thanks a lot for your brilliant plugin! :)) 

One little issue: custom instruction creations do not sync into my vault. There is just a heading called "custom" without any content underneath. 

![voicenotessyncissue](https://github.com/user-attachments/assets/3b221e85-e151-4cb7-be24-7b41c51d4a7a)

**Comment by hjamet** [comment]
Thank you from the bottom of my heart! This bug, like others, should be resolved in the beta currently being rolled out! (CF : https://github.com/mysticcoders/voicenotes-sync/pull/42 ) 🦦

**Comment by kinabalu** [comment]
v0.0.20 fixes this
