### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by cvasanthk** [mysticcoders/voicenotes-sync#47]
There is a new field introduced in 0.0.20 plugin update " Exclude folders" 
Since there is no folder concept in voicenotes, what does this feature do? How do we use it?

**Comment by kinabalu** [comment]
No there shouldn't be, there is an Exclude Tags feature however.

**Comment by cvasanthk** [comment]
<img width="666" alt="image" src="https://github.com/user-attachments/assets/00b64b0e-e0ba-48df-bfab-e0d9de443f0f">
This is what I see in the settings.
