### ISSUE TITLE
Audio file name & place

### ISSUE THREAD

**Issue by yoghurtdewdew** [mysticcoders/voicenotes-sync#49]
I like local offline audio files. Now their file name is ID, I can't sort them by creation date, since I may delete files and resync to keep notes updated. When playing them in a folder, I can't let them play one by one according to creation time, so I hope it is possible to customize the file names of these audio files to the creation time like `YYYY-MM-DD_HHmmss`.

In addition, because the storage space of the whole valut takes up a lot when the synchronous recording file is local. I hope they can be saved in other folders, that is, outside the valut, so that I can realize md files synchronized, but audio files are stored offline, in case they taking up too much synchronization space.

**Comment by kinabalu** [comment]
I've got a quick solve for you on the sync issue, the best way to achieve that is to add them to the excludes list in Obsidian Sync so they aren't counted against.

**Comment by kinabalu** [comment]
what sync method are you using @yoghurtdewdew ? the issue is that saving files in an Obsidian plugin are only allowed to be in the vault, not external.

**Comment by yoghurtdewdew** [comment]
> what sync method are you using @yoghurtdewdew ? the issue is that saving files in an Obsidian plugin are only allowed to be in the vault, not external.

Hi, I use iCloud and syncthing for synchronization, so that files can be used on my different devices.
If files can only be stored in the vault, is it possible to have a button in the plug-in settings interface, and click this button would download the latest updated files to another location? 
Otherwise, it seems that I may have to put the files in vault. Then move the files out of the vault after the download is completed. If I do this every time, I feel there seems to be some trouble.
And I also have a need of customizing the file name as mentioned above.

**Comment by kinabalu** [comment]
You may be able to customize the settings using syncthing for a specific folder not to be synced. I'm fairly certain that software allows for that. As far as changing the name of the audio file, I'd rather not provide that as a configurable option since the creation date would suffice here. Becomes even harder to debug possible issues in the future.

**Comment by yoghurtdewdew** [comment]
Hi, thank you for your hard work and dedication to this plug-in. I wonder if the creation date&time prefix like `20241125_165311_` of these audio files can be considered to be added to the ID names? Because it will be more beneficial for sorting and finding these audio files in the local folder. After all, the creation date of files in the local folder is different from the actual creation date of these audios. In fact, when I update my notes in voicenotes, I have to delete the original file and resynchronize my notes, which will lead to duplicate files. I may be faced with some operations like deleting the original file and downloading it again. These steps will lead to different creation times of files and audio. 
I really hope that I can sort these audio files directly in the folder according to their actual creation date, and then I can directly find a specific audio or listen to the audio in order.
