### ISSUE TITLE
Plugin stopped syncing and Obsidian options page for it is empty

### ISSUE THREAD

**Issue by YorVeX** [mysticcoders/voicenotes-sync#50]
Last things I did was rename some tags, create a new one, create a few text based notes by starting a short but empty recording and then copying text into it (as suggested as a workaround while there is no text entry feature in voicenotes yet). I reverted the tag renaming, but it didn't help.

I keep all vault files on a cloud drive and access them from 2 different computers, so far this hasn't caused any issues, but who knows. Any ideas what I could try to narrow down where the issue is coming from?

![image](https://github.com/user-attachments/assets/5f1f895f-4546-44fd-a312-2bd0f3b31b3c)

**Comment by yshhwy** [comment]
Same here. Does it have something to do with the issue from a few days ago where people’s notes got mixed up?

**Comment by luketech85** [comment]
I have the same issue

**Comment by hjamet** [comment]
I think the problem was with the voicenotes servers. I encourage you to uninstall and reinstall the plugin before connecting again, which should solve the problem. 🦦

**Comment by yshhwy** [comment]
> I think the problem was with the voicenotes servers. I encourage you to uninstall and reinstall the plugin before connecting again, which should solve the problem. 🦦

I don't want to lose the synchronization templates I've already set up, but I can't access the settings panel right now. What should I do? Can I find the settings templates in files elsewhere?

**Comment by kinabalu** [comment]
this is an unfortunate bug that was surfaced with all the recent changes. it assumes you are logged in even if you aren't and doesn't offer you a clear way back if the token is wrong. hotfix in 0.0.21 now and may need another one -- need more folks to test. Please reopen if this fix doesn't help.

**Comment by YorVeX** [comment]
Is the hotfix supposed to make the settings available again by itself or do we still need to manually uninstall and reinstall the plugin to fix it?

I just updated to 0.0.21 and restarted Obsidian, but the Voicenotes Sync plugin settings page is still empty. I will need it soon but can still live with a few more days of this not being available, so for now this is my update report and I can help testing another hotfix if necessary, will not reinstall yet unless there is no way around that anyway.

**Comment by mickahouan** [comment]
> Is the hotfix supposed to make the settings available again by itself or do we still need to manually uninstall and reinstall the plugin to fix it?
> 
> I just updated to 0.0.21 and restarted Obsidian, but the Voicenotes Sync plugin settings page is still empty. I will need it soon but can still live with a few more days of this not being available, so for now this is my update report and I can help testing another hotfix if necessary, will not reinstall yet unless you tell me there is no way around that anyway.

I deleted and reinstalled the plugin manually (brat) and it works again for me.

**Comment by kinabalu** [comment]
give it another try with 0.0.22 and this should fix it. the issue for sure, is that the call to getNotes was assuming the token was valid, and when it wasn't was throwing errors that weren't handled. this way if the token is found to be invalid, it gets nulled out, so you can login again.

i think this happened because voicenotes.com invalidated all logins and required new tokens to be generated. great way to find some hidden bugs and assumptions. please re-open or open a new ticket if you still have trouble after installing 0.0.22 -- thanks!

**Comment by YorVeX** [comment]
Thanks, it's fixed now with 0.022 even without plugin reinstallation.
