### ISSUE TITLE
PLUGIN KEEPS LOSING LOGIN AND NOTE TEMPLATE MALFUNCTIONING 

### ISSUE THREAD

**Issue by Jwminva** [mysticcoders/voicenotes-sync#52]
The plugin keeps logging out and causing the synch to fail. It's also referring to and authentication key that doesn't seem to exist.  The note template is not working either. It's not creating properties anymore. This all happened suddenly after an update this weekend.

**Comment by Jwminva** [comment]
Is anyone else having this issue? This literally just started a couple days ago.

**Comment by Jwminva** [comment]
It's getting pretty annoying. The tasks are not synchronizing either it seems.

**Comment by jor7am** [comment]
me too, you're right, this happen after the last update

**Comment by Jwminva** [comment]
Well, at least it's not just me.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by kinabalu** [comment]
can you perhaps screenshot any relevant settings you have in your installs? not able to recreate yet but would like to figure it out

**Comment by Jwminva** [comment]
Which settings? The voicenotes plug in settings or settings in general? The thing is, I didn't change any settings recently.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by kinabalu** [comment]
code was changed, but trying to recreate your issue so its helpful to see what the voicenotes plugin settings are to try to recreate.

**Comment by Jwminva** [comment]
Yeah I'll try to do some screen prints of what the note looked like before the update to the plug-in and what they look like now because they are definitely different. Like I said as far as I know I didn't change any major settings in anything so clearly something wrong relative to the last update
Sent from Proton Mail Android

-------- Original Message -------- 
On 9/24/24 10:15 PM, Andrew Lombardi wrote: 
code was changed, but trying to recreate your issue so its helpful to see what the voicenotes plugin settings are to try to recreate.

**Comment by robotii** [comment]
The properties not appearing are due to the changes in main.ts

around line 378
```
    ---\n`;
```

needs to be changed back to 
```
---\n`;
```

without the leading spaces, then the properties will work again after a resync.

**Comment by kinabalu** [comment]
Good catch on that -- 0.0.23 has that fix in it. I don't think that's the main issue in the ticket though

**Comment by kinabalu** [comment]
can I get an update if folks are still experiencing this issue?

**Comment by Jwminva** [comment]
The format issue seems to be fixed so the notes generated are creating properties again. However, the login issue is persisting.

**Comment by kinabalu** [comment]
Unable to recreate the issue with login here, I know its happening for some. Are you using the email-based login? or Apple / Google? What are the Settings in your app (excluding the template itself)

**Comment by Jwminva** [comment]
The format issue appears to be fixed because now the notes created in the obsidian vault have properties again like they did previously however the issue with logging out and in to voice notes through the plug-in is still an issue. So if I exit the Vault and re-enter the vault it's not going to sink without me re-entering my account login information again in the plug-in

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Jwminva** [comment]
It keeps asking for a login token when the vault is opened and there is no login token that I'm aware of for voice notes

Sent from Proton Mail Android

-------- Original Message -------- 
On 9/27/24 8:20 PM, JWM_IN_VA wrote: 
The format issue appears to be fixed because now the notes created in the obsidian vault have properties again like they did previously however the issue with logging out and in to voice notes through the plug-in is still an issue. So if I exit the Vault and re-enter the vault it's not going to sink without me re-entering my account login information again in the plug-in
Sent from Proton Mail Android


-------- Original Message -------- 
On 9/27/24 2:35 PM, Andrew Lombardi wrote: 
can I get an update if folks are still experiencing this issue?

**Comment by Jwminva** [comment]
Yes, I'm using the same email login I set up the account with which wasn't having issues until the last update foe the plugin. Then suddenly it wanted an Authentication login which i do not understa

**Comment by kinabalu** [comment]
is it possible that there are moments @Jwminva when you are losing internet and thus the login would fail in some way? the plugin naively assumes that if it receives a failure that the login is wrong.

**Comment by Jwminva** [comment]
No, but I'm a mobile user so not thst has an effect. I don't think so because it was working fine before the update.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Jwminva** [comment]
Apologies for that being completely scrambled due to voice to text issues. I meant to say that I'm a mobile user so the power issue may not have an effect there or shouldn't I would think. Not to mention that in the past it wasn't an issue at all until he update happened. That's when everything started to go wonky.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by kinabalu** [comment]
Can one of the folks who've seen this issue re-test ASAP? This should be fixed with 0.0.26.

**Comment by kinabalu** [comment]
Please reopen if this isn't the case.

**Comment by Jwminva** [comment]
Yes, it appears to be working again.

Sent from Proton Mail Android

-------- Original Message --------
