### ISSUE TITLE
Date Format Does not apply

### ISSUE THREAD

**Issue by matari** [mysticcoders/voicenotes-sync#54]
![image](https://github.com/user-attachments/assets/6935f2e2-fee1-4d6c-817b-e0730d1bfb29)
regardless of the settings entered the moment.js format used is always YYYY-MM-DD.

**Comment by kinabalu** [comment]
sort of. the {{date}} referenced in the filename is the filenameDateFormat which I've added a separate setting for. the existing code was using something called prependDateFormat which was fixed at YYYY-MM-DD and now its separate.

Possible that we might have a new variable called {{filename_date}} to distinguish between both.
