### ISSUE TITLE
Login / sync of voice notes not working with newest version

### ISSUE THREAD

**Issue by NewAiCoder** [mysticcoders/voicenotes-sync#55]
Hey @kinabalu 
I am getting authentication token errors when I sign in via the plugin options and using username/password. I get a popup that says the login was successful but as soon as I try to sync, I get a bunch of errors and no notes are synced. It also seemingly logs me out because the next time I open the plugin options I have to sign in again. The same happens when I re-start Obsidian.

This morning when I first synced notes it worked briefly before these issues started happening.

Here's the console output:

> plugin:voicenotes-sync:58 loginUrl: https://api.voicenotes.com/api/auth/login
> plugin:voicenotes-sync:1543 SyntaxError: Unexpected token ')'
>     at new Function (<anonymous>)
>     at jinja.compile (plugin:voicenotes-sync:1119:13)
>     at jinja.render (plugin:voicenotes-sync:1125:23)
>     at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1497:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:voicenotes-sync:32:58)
> eval @ plugin:voicenotes-sync:1543
> plugin:voicenotes-sync:1543 SyntaxError: Unexpected token ')'
>     at new Function (<anonymous>)
>     at jinja.compile (plugin:voicenotes-sync:1119:13)
>     at jinja.render (plugin:voicenotes-sync:1125:23)
>     at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1497:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:voicenotes-sync:32:58)
> eval @ plugin:voicenotes-sync:1543
> plugin:voicenotes-sync:1543 SyntaxError: Unexpected token ')'
>     at new Function (<anonymous>)
>     at jinja.compile (plugin:voicenotes-sync:1119:13)
>     at jinja.render (plugin:voicenotes-sync:1125:23)
>     at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1497:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:voicenotes-sync:32:58)
> eval @ plugin:voicenotes-sync:1543
> plugin:voicenotes-sync:1543 SyntaxError: Unexpected token ')'
>     at new Function (<anonymous>)
>     at jinja.compile (plugin:voicenotes-sync:1119:13)
>     at jinja.render (plugin:voicenotes-sync:1125:23)
>     at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1497:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:voicenotes-sync:32:58)
> eval @ plugin:voicenotes-sync:1543
> plugin:voicenotes-sync:1543 SyntaxError: Unexpected token ')'
>     at new Function (<anonymous>)
>     at jinja.compile (plugin:voicenotes-sync:1119:13)
>     at jinja.render (plugin:voicenotes-sync:1125:23)
>     at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1497:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (plugin:voicenotes-sync:32:58)
> eval @ plugin:voicenotes-sync:1543

let me know if you need any further information.

**Comment by kinabalu** [comment]
Are you using email-based login or using one of the third party login methods (Apple, Google, Twitter)?

what platform are you using with the Voicenotes Sync plugin? Mobile iOS? Android? Desktop Mac? Windows?

**Comment by NewAiCoder** [comment]
I am using e-mail login.
I am using Obsidian on Windows.

**Comment by NewAiCoder** [comment]
I am still having this issue - is there something I can try?

![image](https://github.com/user-attachments/assets/7a7b1928-a8fd-4816-9ea9-56c87a2a5ba0)

**Comment by kinabalu** [comment]
Under View -> Toggle Developer Tools you should see a lot of content you can screenshot or send the text in the comment here to see what might be happening -- please send this and it should help us figure out whats happening

**Comment by NewAiCoder** [comment]
@kinabalu 
yes that's what I posted in my first post in the thread. Here it is again as a screenshot:

![image](https://github.com/user-attachments/assets/20c2925d-22f2-4149-a5d0-e3aca0416ed9)
![image](https://github.com/user-attachments/assets/c217c699-0591-4913-8cf2-2c17e943def8)

This is what happens if I try to manual sync after putting in my login details. I then get logged out again.

**Comment by andrewlombardictr** [comment]
Please let me know if 0.0.26 which was just released fixes the issue you were seeing.

**Comment by NewAiCoder** [comment]
Yup, that fixed it! thank you!

I had to manually install, though - the update does not show up in the Obsidian Plugin Manager.

**Comment by andrewlombardictr** [comment]
i re-pushed 0.0.26 since I mucked that up, thank you! glad it's working now!

**Comment by kinabalu** [comment]
i re-pushed 0.0.26 since I mucked that up, thank you! glad it's working now!

**Comment by johnlunney** [comment]
I've installed the latest update 26, but still seeing the issue (using token login).

I log in successfully, then as soon as I manual sync, get a bunch of login errors (and get logged out).

**Comment by kinabalu** [comment]
would you mind screenshotting or pasting the errors from the developer tools you're seeing?

**Comment by johnlunney** [comment]
It's hard to get logs on the mobile version, so I set up the desktop app, and it worked there, even in mobile mode.

I deleted and reinstalled the extension on my phone, and it works now. ¯\_(ツ)_/¯

**Comment by kinabalu** [comment]
will close now as maybe it was just a bad key
