### ISSUE TITLE
Plugin does not download audio attachments (BUG)

### ISSUE THREAD

**Issue by Warden20** [mysticcoders/voicenotes-sync#57]
I am using the latest version of the plugin (0.0.24) and obsidian 1.7.4. The plugin synchronizes the notes when I don't have the option to download the audios activated but when I activate it, it doesn't synchronize the notes nor download the audios.
At the end the plugin rejects my credentials and I have to re-enter them.

**Comment by kinabalu** [comment]
I believe that 0.0.26 should fix the credential rejection issue, please re-open if this isn't the case. thanks!
