### ISSUE TITLE
Logging in/out issue

### ISSUE THREAD

**Issue by menagerie198** [mysticcoders/voicenotes-sync#61]
Each time I reopen Obsidian I find that the Voicenotes Sync plugin has logged out. Any ideas why that might be, and/or how to remain logged in across sessions?

**Comment by medo2132112** [comment]
+1 ... I am logged in via token

**Comment by Jwminva** [comment]
Same...just started today again. What is causing this?! I thought it was fixed???

**Comment by Jwminva** [comment]
> +1 ... I am logged in via token

How?? I could not find the token for my account anywhere.

**Comment by Jwminva** [comment]
Okay so it's even worse. It's logging out even during the sessions!! What the hell is this?!

**Comment by kinabalu** [comment]
Hey folks, I hear that the token login is acting erratically for some folks. Would love to get to the bottom of this!

If someone can open View -> Toggle Developer Tools and copy anything that looks like an error that is coming from Voicenotes and paste it here, that will help immensely. 

Also, please indicate which token login you're currently using, Twitter, Apple, Google.

And lastly if anyone has a sense of time between when they last synced voicenotes and when it appeared to logout. that would be helpful as well.

Initial thought is this might be a timeout issue but need more data from folks, thank you!

**Comment by Jwminva** [comment]
Not using any of those tokin logins. Not sure how that relates. It started yesterday Saturday and was working Friday evening. I didn't see an update to the plugin either. 

Sent from Proton Mail Android

-------- Original Message -------- 
On 11/23/24 11:10 PM, Andrew Lombardi wrote: 
Hey folks, I hear that the token login is acting erratically for some folks. Would love to get to the bottom of this!
If someone can open View -> Toggle Developer Tools and copy anything that looks like an error that is coming from Voicenotes and paste it here, that will help immensely.
Also, please indicate which token login you're currently using, Twitter, Apple, Google.
And lastly if anyone has a sense of time between when they last synced voicenotes and when it appeared to logout. that would be helpful as well.
Initial thought is this might be a timeout issue but need more data from folks, thank you!

**Comment by Jwminva** [comment]
I don't see Developer Tools when I log in via desktop. Where is it exactly??

**Comment by menagerie198** [comment]
Developer Tools is (in Windows at least) via Ctrl+Shft+i

Re password disappearing... might this be helpful (all greek to me I'm afraid), from the error console:

2plugin:voicenotes-sync:1543 TypeError: Cannot read properties of null (reading 'saving')
    at t.<anonymous> (app.js:1:735786)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at g (app.js:1:235994)
    at t.modify (app.js:1:735690)
    at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1529:46)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:voicenotes-sync:32:58)

**Comment by menagerie198** [comment]
I do not use tokens -- only log-in to my Voicenotes account.

**Comment by medo2132112** [comment]
> +1 ... I am logged in via token

I did it because I can't log in with my email normally. I think it's becauseI created my account using a Google account and encountered this issue

**Comment by kinabalu** [comment]
Please test with the latest version 0.0.27 just released.

And if you want to paste your Custom Note Template here, I can review. I think there may be some templates that don't sync down because the Custom Note Template has a variable in it that the plugin can't find but can't say until I see it. 

If that doesn't fix this please re-open. Thanks!

**Comment by menagerie198** [comment]
Obsidian was not finding 0.0.27, so I downloaded the zip from here and installed manually. Will let you know how it pans out later. Thanks for addressing this so quickly - great plugin that I use every day! Cheers

**Comment by menagerie198** [comment]
I just logged in to Voicenotes (v0.0.27), cosed and reopened Obsidian. Voice notes is now logged out! This is what the console says:
plugin:voicenotes-sync:1543 TypeError: Cannot read properties of null (reading 'saving')
    at t.<anonymous> (app.js:1:735786)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at g (app.js:1:235994)
    at t.modify (app.js:1:735690)
    at VoiceNotesPlugin.eval (plugin:voicenotes-sync:1529:46)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:voicenotes-sync:32:58)
eval	@	plugin:voicenotes-sync:1543

**Comment by medo2132112** [comment]
Yes, that's mine I kept it normal
> Please test with the latest version 0.0.27 just released.
> 
> And if you want to paste your Custom Note Template here, I can review. I think there may be some templates that don't sync down because the Custom Note Template has a variable in it that the plugin can't find but can't say until I see it.
> 
> If that doesn't fix this please re-open. Thanks!
# {{ title }}

Date: {{ date }}

{% if summary %}
## Summary

{{ summary }}
{% endif %}

{% if points %}
## Main points

{{ points }}
{% endif %}

{% if attachments %}
## Attachments

{{ attachments }}
{% endif %}

{% if tidy %}
## Tidy Transcript

{{ tidy }}

{% else %}
## Transcript

{{ transcript }}
{% endif %}

{% if audio_link %}
[Audio]({{ audio_link }})
{% endif %}

{% if todo %}
## Todos

{{ todo }}
{% endif %}

{% if email %}
## Email

{{ email }}
{% endif %}

{% if blog %}
## Blog

{{ blog }}
{% endif %}

{% if tweet %}
## Tweet

{{ tweet }}
{% endif %}

{% if custom %}
## Others

{{ custom }}
{% endif %}

{% if tags %}
## Tags

{{ tags }}
{% endif %}

{% if related_notes %}
# Related Notes

{{ related_notes }}
{% endif %}

{% if parent_note %}
## Parent Note

- {{ parent_note }}
{% endif %}

{% if subnotes %}
## Subnotes

{{ subnotes }}
{% endif %}

**Comment by kinabalu** [comment]
Just released 0.0.28 which should add more logging data in this specific error case, if one of you who've experienced this can test again @menagerie198 or @medo2132112 or both, would love to see the logs after it logs out with that error.

thank you!

**Comment by Jwminva** [comment]
The issues seemed to have stopped yesterday afternoon. It's not logging out. Regarding custom templates, I don't use any.

**Comment by menagerie198** [comment]
I think I am just using the default template:
# {{ title }}
Date: {{ date }}

{% if summary %}
## Summary
{{ summary }}
{% endif %}

{% if points %}
## Main points
{{ points }}
{% endif %}

{% if attachments %}
## Attachments
{{ attachments }}
{% endif %}

{% if tidy %}
## Tidy Transcript
{{ tidy }}

{% else %}
## Transcript
{{ transcript }}
{% endif %}

{% if audio_link %}
[Audio]({{ audio_link }})
{% endif %}

{% if todo %}
## Todos
{{ todo }}
{% endif %}

{% if email %}
## Email
{{ email }}
{% endif %}

{% if blog %}
## Blog
{{ blog }}
{% endif %}

{% if custom %}
## Others
{{ custom }}
{% endif %}

{% if tags %}
## Tags
{{ tags }}
{% endif %}

{% if related_notes %}
# Related Notes
{{ related_notes }}
{% endif %}

{% if parent_note %}
## Parent Note
- {{ parent_note }}
{% endif %}

{% if subnotes %}
## Subnotes
{{ subnotes }}
{% endif %}

**Comment by Jwminva** [comment]
Okay...what the hell are you all doing now?! The plugin was working again and now it's having the login issues again. WTF?!?!.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by kinabalu** [comment]
0.0.28 should be released again, a beta got out into the wild.

**Comment by Jwminva** [comment]
The log out issue seems resolved but the template is missing the tags property element upon generation of the note in the vault.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by medo2132112** [comment]
Thanks for solving the problem

> 0.0.28 should be released again, a beta got out into the wild.

**Comment by menagerie198** [comment]
Login persists for me now... many thanks Andrew!

**Comment by Jwminva** [comment]
Login issues again...this has got to stop.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by kinabalu** [comment]
Nothing has changed in the codebase for the sync tool. Perhaps there's something else going on. I appreciate your comment on the issue, but please try to copy and paste from developer tools to see if we can figure out what the problem is.
