### ISSUE TITLE
I don't see any folder voicenotes

### ISSUE THREAD

**Issue by mickahouan** [mysticcoders/voicenotes-sync#7]
The plugin is installed, but I don't see a Voicenotes folder on Obsidian. PS: I've also tried manual synchronization.
![Capture d'écran 2024-05-13 161841](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/318b6e72-6254-4cc3-b16f-fcdc9ef51cec)

**Comment by andrewlombardictr** [comment]
if you Toggle Developer Tools and look at the logs, anything in there indicating an error with voicenotes?

**Comment by mickahouan** [comment]
Yes. Maybe I need to create the Voicenotes file manually?
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/802b7d9d-5d3c-46e3-b4e5-741882665d46)

**Comment by mickahouan** [comment]
Creating the file solved the problem
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/f5941377-6e49-45de-8f6b-97df95501753)

**Comment by kinabalu** [comment]
this has been fixed in 0.0.5. had a bug that was not doing something in code which would create that folder. fixed now.
