### ISSUE TITLE
Characters with accents are not well rendered in import (in titles)

### ISSUE THREAD

**Issue by mickahouan** [mysticcoders/voicenotes-sync#8]
Characters with accents do not appear in titles Characters such as ' é è ê, etc. do not appear in titles. These characters are widely used in the French language.

Exemples : 
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/9cf41b58-8180-4ce9-844e-9dbb4785e778)

As a reminder, here are the characters you can't use for titles in Obsidian :
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/88fc1863-9298-4f66-9a1a-c9a4fa10b0ed)

**Comment by kinabalu** [comment]
0.0.5 has a fix which should respect any non-english characters. please test and let me know, thank you!

**Comment by mickahouan** [comment]
Thanks for the update. Problem #7 is now solved. However: characters with accents are still missing. 
In my files, here for example, they are missing: 
- é
- ê
- '
- I assume the same will be true for : - è
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/1b45ac3e-4807-442d-871f-90585229bf0e)

![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/dcafc9a1-4a3b-4fee-a7b4-620fd2b4b530)
