### ISSUE TITLE
Thanks for the update. Problem #7 is now solved. However: characters with accents are still missing.

### ISSUE THREAD

**Issue by mickahouan** [mysticcoders/voicenotes-sync#9]
Thanks for the update. Problem #7 is now solved. However: characters with accents are still missing. 
In my files, here for example, they are missing: 
- é
- ê
- '
- I assume the same will be true for : - è
![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/1b45ac3e-4807-442d-871f-90585229bf0e)

![image](https://github.com/mysticcoders/voicenotes-sync/assets/31423109/dcafc9a1-4a3b-4fee-a7b4-620fd2b4b530)

_Originally posted by @mickahouan in https://github.com/mysticcoders/voicenotes-sync/issues/8#issuecomment-2109238332_

**Comment by kinabalu** [comment]
Could you paste in some titles perhaps which I can use for testing?

**Comment by mickahouan** [comment]
Réfléchir, lire et écrire pour comprendre et intégrer les idées
Huit étapes pour éditer un article - Premières notes
Critique des systèmes complexes et l'utilité que les plugins Obsidian peuvent revêtir

**Comment by kinabalu** [comment]
ok tested and should be fixed in 0.0.6
